---
name: Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0

      - name: Install LocalStack Tools
        id: install_localstack_tools
        run: |
          pip install --requirement requirements-dev.txt

      - name: Test
        id: test
        shell: bash
        run: |
          make test
